apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.commonVolume.name }}
spec:
  # storageClassName: fast
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
